name: taskaia
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.1
  get_storage: ^2.0.3
  sqflite: ^2.0.2
  path: ^1.8.0
  image_picker: ^0.8.5
  path_provider: ^2.0.9
  intl: ^0.17.0
  flutter_staggered_animations: ^1.0.0
  flutter_screenutil: ^5.3.1
  flutter_svg: ^1.0.3
  liquid_swipe: ^2.1.1
  smooth_page_indicator: ^1.0.0+2
  url_launcher: ^6.0.20

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_native_splash: ^2.1.5

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo.png
  color_dark: "#08141f"
  android: true
  ios: true

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf

