Map<String, String> ar = {
  'app_title': 'Taskaia',
  'notes': 'الملاحظات',
  'tasks': 'المهام',
  'memories': 'الذكريات',
  'title': 'العنوان',
  'title_hint': 'ادخل العنوان هنا',
  'title_verify': 'برجاء ادخال العنوان المطلوب !',
  'description': 'الوصف',
  'description_hint': 'ادخل الوصف هنا',
  'description_verify': 'برجاء ادخال الوصف المطلوب !',
  'datetime': 'التاريخ',
  'datetime_hint': 'ادخل التاريخ هنا',
  'datetime_verify': 'برجاء تحديد التاريخ المطلوب !',
  'image': 'الصورة',
  'start_time': 'وقت البدء',
  'start_time_hint': 'ادخل وقت البدء هنا',
  'start_time_verify': 'برجاء تحديد وقت البدء المطلوب !',
  'end_time': 'وقت الانتهاء',
  'end_time_hint': 'ادخل وقت الانتهاء هنا',
  'end_time_verify': 'برجاء تحديد وقت الانتهاء المطلوب !',
  'reminder': 'التذكرة',
  'reminder_hint': 'ادخل التذكرة هنا',
  'reminder_verify': 'برجاء تحديد التذكرة المطلوبه !',
  'repeat': 'التكرار',
  'repeat_hint': 'ادخل التكرار هنا',
  'repeat_verify': 'رجاء تحديد عدد التكرار المطلوب !',
  'color': 'اللون',
  'create': 'انشاء',
  'create_note': 'انشاء ملاحظة',
  'create_task': 'انشاء مهمة',
  'create_memory': 'انشاء ذكرى',
  'today': 'اليوم',
  'completed_task': 'اكمال المهمة',
  'completed': 'مكتملة',
  'un_completed': 'غير مكتملة',
  'update': 'تعديل',
  'delete': 'حذف',
  'cancel': 'رجوع',
  'ok': 'تم',
  'error': 'خطأ',
  'image_error': 'برجاء تحديد الصورة !',
  'skip': 'تخطي',
  'next': 'التالي',
  'onboarding_1': 'قم بعمل أفضل ما لديك في كل ملاحظة.',
  'onboarding_2':
      'قم بتدوين الملاحظات والمهام والذكريات وابحث عن موضوع في أي وقت.',
  'onboarding_3': 'اعملوا معًا وانجزوا المهمة.',
  'get_started': 'أبدأ',
  'none': 'لا شىء',
  'daily': 'يومي',
  'weekly': 'اسبوعي',
  'monthly': 'شهري',
  'about_app': 'عن التطبيق',
  'about_app_description': 'Taskaia هو تطبيق مجاني يمكنك من كتابة ما تريده من ملاحظات أو انجاز بعض المهام أو كتابة ذكريات خاصة بك.'
};
