Map<String, String> en = {
  'app_title': 'Taskaia',
  'notes': 'Notes',
  'tasks': 'Tasks',
  'memories': 'Memories',
  'title': 'Title',
  'title_hint': 'Enter your title here',
  'title_verify': 'Enter title please !',
  'description': 'Description',
  'description_hint': 'Enter your description here',
  'description_verify': 'Enter description please !',
  'datetime': 'Datetime',
  'datetime_hint': 'Detect datetime here',
  'datetime_verify': 'Enter datetime please !',
  'image': 'Image',
  'start_time': 'Start time',
  'start_time_hint': 'Detect start time here',
  'start_time_verify': 'Enter start time please !',
  'end_time': 'End time',
  'end_time_hint': 'Detect end time here',
  'end_time_verify': 'Enter end time please !',
  'reminder': 'Reminder',
  'reminder_hint': 'Detect reminder here',
  'reminder_verify': 'Enter reminder please !',
  'repeat': 'Repeat',
  'repeat_hint': 'Detect repeat here',
  'repeat_verify': 'Enter repeat please !',
  'color': 'Color',
  'create': 'Create',
  'create_note': 'Create Note',
  'create_task': 'Create Task',
  'create_memory': 'Create Memory',
  'today': 'Today',
  'completed_task': 'Complete task',
  'completed': 'Completed',
  'un_completed': 'Un Completed',
  'update': 'Update',
  'delete': 'Delete',
  'cancel': 'Cancel',
  'ok': 'OK',
  'error': 'Error',
  'image_error': 'You should pick the image !',
  'skip': 'Skip',
  'next': 'Next',
  'onboarding_1': 'Do your best work ever in every note.',
  'onboarding_2': 'Take notes, tasks and memories and find theme on any time.',
  'onboarding_3': 'Work together and get the job done.',
  'get_started': 'Get started',
  'none': 'None',
  'daily': 'Daily',
  'weekly': 'Weekly',
  'monthly': 'Monthly',
  'about_app': 'About application',
  'about_app_description': 'Taskaia app is a free application that enables you to write whatever you want from notes, accomplish some tasks, or write your own memories.'
};
